### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by RushilPatel0703** [soniabullah1/COMS3009A-Agile-Sprinters#2]
In my Androidmanifest.xml, everything is being highlighted

**Comment by soniabullah1** [comment]
Does it not tell you what the error is if you hover your mouse over the highlighted section?

**Comment by RushilPatel0703** [comment]
Yes I tried that but i was just told that everything did not belong there, in simple terms.

**Comment by RushilPatel0703** [comment]
fixed it
